### ISSUE TITLE
Use with categorical variable

### ISSUE THREAD

**Issue by gdagstn** [flying-sheep/ggplot.multistats#1]
Hi, this is an excellent package. 

Do you have any suggestion on what's the best way to represent a categorical variable as well?
E.g. if in any hexagon I wanted to see which of my factor levels is most represented as a colour from a qualitative palette.

Cheers!

**Comment by flying-sheep** [comment]
Thank you, happy you like it!

If I understand you correctly, this already works fine:

```r
# group all together, else the discrete colors mess up the bins
ggplot(iris, aes(Sepal.Width, Sepal.Length, group = 1)) +
    stat_summaries_hex(
        aes(z = Species, fill = stat(most), alpha = stat(n)),
        funs = list(most = function(s) names(which.max(summary(s))), n = 'length'),
        bins = 5
    )
```
![grafik](https://user-images.githubusercontent.com/291575/70373698-d4cf7100-18ea-11ea-9129-e4ac78a90b23.png)

I’ll close this for now, but if you wanted something else, please tell me and I’ll reopen
