### ISSUE TITLE
Unable To Reproduce Example, z Aesthetic Is Dropped:

### ISSUE THREAD

**Issue by JStorey42** [flying-sheep/ggplot.multistats#2]
stat_summaries_hex seems to be exactly what I'm looking for!

However, I'm unable to reproduce the example and am wondering if I'm missing something or if an update has caused some incompatibility? When specifying both fill and alpha values with stats, only the alpha value appears to make an effect. If I remove the alpha parameter, then the hex bins are colored by n but only when alpha is not specified. 

In addition, I'm receiving the warning message that the z aesthetic was dropped during statistical transformation - I assume that shouldn't happen, as the z aesthetic is what I'm trying to transform!

I have ggplot.multistats 1.0.0 and ggplot2 3.4.0 installed.

```
library(ggplot2)
library(ggplot.multistats)

ggplot(iris, aes(Sepal.Width, Sepal.Length)) +
  stat_summaries_hex(
    aes(z = Petal.Width, fill = stat(median), alpha = stat(n)),
    funs = c('median', n = 'length'),
    bins = 5
  )
```
![image](https://user-images.githubusercontent.com/52438403/210010309-35d9770b-e2c5-4896-aab8-140a57eb511c.png)

**Comment by flying-sheep** [comment]
It’s a warning, and https://github.com/tidyverse/ggplot2/issues/5053 implies that it doesn’t indicate that anything went wrong. Indeed the plot looks correct, doesn’t it?

I made #3 to get rid of warnings.
