### ISSUE TITLE
Release v1.0.1

### ISSUE THREAD

**Issue by flying-sheep** [flying-sheep/ggplot.multistats#4]
CRAN team is on vacation rn

**Comment by flying-sheep** [comment]
ah lol and of course I try again when they’re on vacation again

**Comment by dtm2451** [comment]
Wondering if you have plans to try submitting again?  CRAN submsisions queue seems open currently.

Luckily, plotting behavior seems fine, but I get warnings like the below when using `ggplot.multistats::stat_summaries_hex()` installed from CRAN.

```
Warning message:
The following aesthetics were dropped during statistical transformation: z.
ℹ This can happen when ggplot fails to infer the correct grouping structure in the data.
ℹ Did you forget to specify a `group` aesthetic or to convert a numerical variable into a factor?
```

Zero warnings (and same plots as far as I've noticed) after I install from GitHub!

**Comment by flying-sheep** [comment]
Ah, I forgot, sorry. I’ll do it tomorrow when I have access to an R environment.

I wonder if there’s some GH actions workflow that would create a release for us, then I wouldn’t be dependent on a local R env and could do this whenever.

**Comment by flying-sheep** [comment]
OK, submitted!

**Comment by flying-sheep** [comment]
@dtm2451 seems like it never made its way onto CRAN.

I re-submitted and now everything works and it’s up!
